app = "theeace-login-portal"
primary_region = "iad" # This is Washington DC - change if needed

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "theeace_data"
  destination = "/app/data" 